name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        config:
          - arch: x86-64
            config: ARCH=x86-64 PREFIX=/workspace/opt/openssh __all__/VERSION=latest
            description: x86-64

    env:
      MAKEFLAGS: SHELL=/usr/bin/bash

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y upx

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Build
        run: |
          make config ${{ matrix.config.config }}
          make -j${{ steps.cpu-cores.outputs.count }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ssh-binaries-for-${{ matrix.config.description }}
          path: |
            output/${{ matrix.config.arch }}/bin/
